import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Roboto } from 'next/font/google'

import "./globals.css";
import Link from "next/link";
// import AdSlot from "@/components/AdSlot";
import Script from "next/script";
import GoogleAdComp from "@/components/GoogleAdComp";

const myFont = localFont({
  src: '../fonts/PopJoyStd-B.otf',
  display: 'swap',
  // style: 'normal',
  // weight: '400',
})

// const roboto = Roboto({
//   weight: '400',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: "my-next-blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google AdSense Script */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3457241956721444"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body className={myFont.className}>
        {/* <Navbar /> */}
        <nav className="bg-gray-800 text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-lg font-bold">
              My Next Blog
            </Link>
            {/* <div>
              <Link href="/articles/new" className="px-4 py-2 border text-white rounded hover:bg-gray-900">
                Add New Article
              </Link>
            </div> */}
          </div>
        </nav>

        <div className="flex justify-center">
          {/* Left Ad */}
          <div className="hidden lg:block w-[160px] p-2">
            <div className="sticky top-10">
              <GoogleAdComp />
            </div>
          </div>

          {/* Main Content */}
          <main className="max-w-4xl w-full p-6">{children}</main>

          {/* Right Ad */}
          <div className="hidden lg:block w-[160px] p-2">
            <div className="sticky top-10">
              <GoogleAdComp />
            </div>
          </div>
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
